# TODO: Наполнить

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Мониторим сам Прометей
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Мониторим сервисы на ПК1 (опрос идет через доменное имя pc1-server,
  # которое резолвится через extra_hosts в docker-compose из переменной PC1_LAN_IP в .env)
  - job_name: "pc1_services"
    static_configs:
      - targets: 
          - "pc1-server:80" # Опрос сервисов через Caddy прокси на ПК1