# TODO: Наполнить

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Мониторим сам Прометей
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  # Мониторим сервисы на ПК1 (если они будут отдавать метрики)
  - job_name: "pc1-node-exporter"
    # Prometheus не поддерживает переменные окружения в targets по умолчанию.
    # Замените на реальный IP (например, 192.168.0.10)
    static_configs:
      - targets:
        - "pc1-lan:9100" # Пример для API на ПК1
  - job_name: "pc1-gpu-exporter"
    static_configs:
      - targets:
        - "pc1-lan:9835"
