global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Мониторим сам Прометей
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Мониторим node-exporter на ПК1
  # Имя pc1-server резолвится через extra_hosts в docker-compose из переменной PC1_LAN_IP в .env
  - job_name: "pc1-node-exporter"
    static_configs:
      - targets:
        - "pc1-lan:9100" # Пример для API на ПК1
  - job_name: "pc1-gpu-exporter"
    static_configs:
      - targets:
        - "pc1-lan:9835"